download_eaglei <- function(year) {
  eaglei_file_ids <- list(
    `2014` = "42547717",
    `2015` = "42547822",
    `2016` = "42547825",
    `2017` = "42547828",
    `2018` = "42547879",
    `2019` = "42547885",
    `2020` = "42547894",
    `2021` = "42547891",
    `2022` = "42547897",
    `2023` = "44574907",
    `2024` = "53581661"
  )
  eagelei_url <- paste0(
    "https://figshare.com/ndownloader/files/",
    eaglei_file_ids[as.character(year)]
  )

  exposhur_dir <- file.path(tempdir(), "exposhur")
  if (!dir.exists(exposhur_dir)) {
    dir.create(exposhur_dir)
  }

  exposhur_csv_path <- file.path(exposhur_dir, paste0(year, "_eaglei.csv"))

  if (!file.exists(exposhur_csv_path)) {
    prior_timeout <- getOption("timeout")
    options(timeout = 5 * 60)
    download.file(eagelei_url, exposhur_csv_path, quiet = TRUE)
    options(timeout = prior_timeout)
  }

  exposhur_csv_path
}

#' Download Outage Data
#'
#' @description
#' Downloadeds publically available EAGLE-I data published
#' by [Brelsford et al.](https://www.nature.com/articles/s41597-024-03095-5)
#'
#' @details
#' ## Customer Estimates
#' Customer estimates are generated by adding the number of households
#' ([ACS](https://censusreporter.org/tables/B11001/) centered on year of
#' storm) and number of establishments
#' ([Census SUSB](https://www.census.gov/programs-surveys/susb/data/tables.html)
#' for year of storm) per county, getting the percentage of households and
#' establishments per county by state, and multiplying the percentage by the
#' total number of customers in a state ([EIA](https://www.eia.gov/electricity/data/browser/#/topic/56?agg=0,1&geo=g&endsec=vg&linechart=ELEC.CUSTOMERS.US-ALL.A~ELEC.CUSTOMERS.US-RES.A~ELEC.CUSTOMERS.US-COM.A~ELEC.CUSTOMERS.US-IND.A&columnchart=ELEC.CUSTOMERS.US-ALL.A~ELEC.CUSTOMERS.US-RES.A~ELEC.CUSTOMERS.US-COM.A~ELEC.CUSTOMERS.US-IND.A&map=ELEC.CUSTOMERS.US-ALL.A&freq=A&start=2008&end=2023&ctype=map&ltype=pin&rtype=s&maptype=0&rse=0&pin=)
#' year of storm)
#'
#' @param year Year to get outage data for
#'
#' @return raw eaglei data with est_cusomters generated with the procedure described in details
#'
#' @export
#'
#' @examples
#' \dontrun{
#' harvey_eaglei <- get_eaglei(2017)
#' }
get_eaglei <- function(year) {
  eaglei <- download_eaglei(year) |>
    read.csv()
  eaglei$fips_code <- sprintf("%05d", eaglei$fips_code)

  customer_est <- generate_pop_est(year)

  merge(eaglei, customer_est, by.x = "fips_code", by.y = "geoid")
}

generate_pop_est <- function(year) {
  naics_year <- 5 * as.integer((year - 2) / 5) + 2
  naics_param = paste0("NAICS", naics_year)

  est_estab <- httr2::request("https://api.census.gov/data/") |>
    httr2::req_url_path_append(year, "cbp") |>
    httr2::req_url_query(
      get = "ESTAB",
      `for` = "county:*",
      !!naics_param := "00"
    ) |>
    httr2::req_perform() |>
    httr2::resp_body_json(simplifyVector = TRUE) |>
    as.data.frame()

  colnames(est_estab) <- est_estab[1, ]
  est_estab <- est_estab[-1, ]

  est_estab$ESTAB <- as.integer(est_estab$ESTAB)

  est_pop <- httr2::request("https://api.census.gov/data/") |>
    httr2::req_url_path_append(year + 2, "acs", "acs5") |>
    httr2::req_url_query(
      get = "B01001_001E",
      `for` = "county:*",
    ) |>
    httr2::req_perform() |>
    httr2::resp_body_json(simplifyVector = TRUE) |>
    as.data.frame()

  colnames(est_pop) <- est_pop[1, ]
  est_pop <- est_pop[-1, ]

  est_pop$B01001_001E <- as.integer(est_pop$B01001_001E)

  state_customers <- httr2::request(
    "https://www.eia.gov/electricity/data/browser/data/index.php?"
  ) |>
    httr2::req_url_query(
      method = "getMapData",
      geosetId = "ELEC.CUSTOMERS.ALL.A",
      freq = "A",
      topic = 56
    ) |>
    httr2::req_perform() |>
    httr2::resp_body_json(simplifyVector = TRUE)

  state_customers <- state_customers$DATA[[as.character(year)]]
  stabbr = gsub("US-", "", names(state_customers), fixed = TRUE)
  names(state_customers) <- stabbr_to_fips[stabbr]
  state_customers <- unlist(state_customers)

  total_est <- merge(est_estab, est_pop, by = c("state", "county"))
  total_est$est_customers <- total_est$ESTAB + total_est$B01001_001E

  total_est <- lapply(
    split(total_est, total_est$state),
    function(state_df) {
      total <- sum(state_df$est_customers)
      state <- state_df$state[1]
      state_df$est_customers <- state_df$est_customers /
        total *
        state_customers[state]

      state_df
    }
  ) |>
    unsplit(total_est$state)

  total_est$geoid <- paste0(total_est$state, total_est$county)
  total_est[c("geoid", "est_customers")]
}

#' @export
stabbr_to_fips <- c(
  AL = "01",
  AK = "02",
  AZ = "04",
  AR = "05",
  CA = "06",
  CO = "08",
  CT = "09",
  DE = "10",
  DC = "11",
  FL = "12",
  GA = "13",
  HI = "15",
  ID = "16",
  IL = "17",
  IN = "18",
  IA = "19",
  KS = "20",
  KY = "21",
  LA = "22",
  ME = "23",
  MD = "24",
  MA = "25",
  MI = "26",
  MN = "27",
  MS = "28",
  MO = "29",
  MT = "30",
  NE = "31",
  NV = "32",
  NH = "33",
  NJ = "34",
  NM = "35",
  NY = "36",
  NC = "37",
  ND = "38",
  OH = "39",
  OK = "40",
  OR = "41",
  PA = "42",
  RI = "44",
  SC = "45",
  SD = "46",
  TN = "47",
  TX = "48",
  UT = "49",
  VT = "50",
  VA = "51",
  WA = "53",
  WV = "54",
  WI = "55",
  WY = "56",
  AS = "60",
  GU = "66",
  MP = "69",
  PR = "72",
  UM = "74",
  VI = "78"
)
